version: '3.5'

services:
  postgres:
    container_name: ruledb
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./src/migration/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped

volumes:
  postgres:

networks:
  postgres:
    driver: bridge
